server:
  port: 8080

  #mysql
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: root

  #mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/example/*/mapper/xml/*.xml
  type-aliases-package: com.example.user.entity
