server:
  port: 8090

spring:
  application:
    name: ROY-ZUUL


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/

zuul:
  routes:
    order:
      path: /roy-order/**
      serviceId: ROY-ORDER
    goods:
      path: /roy-goods/**
      serviceId: ROY-GOODS
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 5000